### ISSUE TITLE
Crash at main menu after call to music(24)

### ISSUE THREAD

**Issue by 16BitWonder** [nxengine/nxengine-evo#110]
Compiling from the latest commit ([18a2bcf](https://github.com/nxengine/nxengine-evo/tree/18a2bcf513c2ac70a6fda70f17c97fee145e25c2)) and attempting to run the program on either Linux or Windows platforms results in a crash immediately following a call to music(24).
Below are the build and runtime/backtrace logs. (Built and ran on Linux)

Build Log:
```
Cloning into 'nxengine-evo'...
remote: Enumerating objects: 371, done.
remote: Counting objects: 100% (371/371), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 4068 (delta 204), reused 269 (delta 153), pack-reused 3697
Receiving objects: 100% (4068/4068), 5.64 MiB | 6.77 MiB/s, done.
Resolving deltas: 100% (2685/2685), done.
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
/usr/include/SDL2
/usr/lib/x86_64-linux-gnu/libSDL2_mixer.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
debug mode
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mint/Desktop/nxengine-evo/build
Scanning dependencies of target nx
[  1%] Building CXX object CMakeFiles/nx.dir/src/ObjManager.cpp.o
[  1%] Building CXX object CMakeFiles/nx.dir/src/ResourceManager.cpp.o
[  2%] Building CXX object CMakeFiles/nx.dir/src/caret.cpp.o
[  3%] Building CXX object CMakeFiles/nx.dir/src/console.cpp.o
[  3%] Building CXX object CMakeFiles/nx.dir/src/debug.cpp.o
[  4%] Building CXX object CMakeFiles/nx.dir/src/floattext.cpp.o
[  5%] Building CXX object CMakeFiles/nx.dir/src/game.cpp.o
[  5%] Building CXX object CMakeFiles/nx.dir/src/input.cpp.o
[  6%] Building CXX object CMakeFiles/nx.dir/src/inventory.cpp.o
[  7%] Building CXX object CMakeFiles/nx.dir/src/main.cpp.o
[  8%] Building CXX object CMakeFiles/nx.dir/src/map.cpp.o
[  8%] Building CXX object CMakeFiles/nx.dir/src/map_system.cpp.o
[  9%] Building CXX object CMakeFiles/nx.dir/src/niku.cpp.o
[ 10%] Building CXX object CMakeFiles/nx.dir/src/nx_math.cpp.o
[ 10%] Building CXX object CMakeFiles/nx.dir/src/object.cpp.o
[ 11%] Building CXX object CMakeFiles/nx.dir/src/p_arms.cpp.o
[ 12%] Building CXX object CMakeFiles/nx.dir/src/player.cpp.o
[ 13%] Building CXX object CMakeFiles/nx.dir/src/playerstats.cpp.o
[ 13%] Building CXX object CMakeFiles/nx.dir/src/profile.cpp.o
[ 14%] Building CXX object CMakeFiles/nx.dir/src/screeneffect.cpp.o
[ 15%] Building CXX object CMakeFiles/nx.dir/src/settings.cpp.o
[ 15%] Building CXX object CMakeFiles/nx.dir/src/slope.cpp.o
[ 16%] Building CXX object CMakeFiles/nx.dir/src/stageboss.cpp.o
[ 17%] Building CXX object CMakeFiles/nx.dir/src/stagedata.cpp.o
[ 17%] Building CXX object CMakeFiles/nx.dir/src/statusbar.cpp.o
[ 18%] Building CXX object CMakeFiles/nx.dir/src/trig.cpp.o
[ 19%] Building CXX object CMakeFiles/nx.dir/src/tsc.cpp.o
[ 20%] Building CXX object CMakeFiles/nx.dir/src/TextBox/ItemImage.cpp.o
[ 20%] Building CXX object CMakeFiles/nx.dir/src/TextBox/SaveSelect.cpp.o
[ 21%] Building CXX object CMakeFiles/nx.dir/src/TextBox/StageSelect.cpp.o
[ 22%] Building CXX object CMakeFiles/nx.dir/src/TextBox/TextBox.cpp.o
[ 22%] Building CXX object CMakeFiles/nx.dir/src/TextBox/YesNoPrompt.cpp.o
[ 23%] Building CXX object CMakeFiles/nx.dir/src/ai/IrregularBBox.cpp.o
[ 24%] Building CXX object CMakeFiles/nx.dir/src/ai/ai.cpp.o
[ 24%] Building CXX object CMakeFiles/nx.dir/src/ai/almond/almond.cpp.o
[ 25%] Building CXX object CMakeFiles/nx.dir/src/ai/balrog_common.cpp.o
[ 26%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/balfrog.cpp.o
[ 27%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/ballos.cpp.o
[ 27%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/core.cpp.o
[ 28%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/heavypress.cpp.o
[ 29%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/ironhead.cpp.o
[ 29%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/omega.cpp.o
[ 30%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/sisters.cpp.o
[ 31%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/undead_core.cpp.o
[ 32%] Building CXX object CMakeFiles/nx.dir/src/ai/boss/x.cpp.o
[ 32%] Building CXX object CMakeFiles/nx.dir/src/ai/egg/egg.cpp.o
[ 33%] Building CXX object CMakeFiles/nx.dir/src/ai/egg/egg2.cpp.o
[ 34%] Building CXX object CMakeFiles/nx.dir/src/ai/egg/igor.cpp.o
[ 34%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/balcony.cpp.o
[ 35%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/doctor.cpp.o
[ 36%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/doctor_common.cpp.o
[ 36%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/doctor_frenzied.cpp.o
[ 37%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/final_misc.cpp.o
[ 38%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/misery.cpp.o
[ 39%] Building CXX object CMakeFiles/nx.dir/src/ai/final_battle/sidekicks.cpp.o
[ 39%] Building CXX object CMakeFiles/nx.dir/src/ai/first_cave/first_cave.cpp.o
[ 40%] Building CXX object CMakeFiles/nx.dir/src/ai/hell/ballos_misc.cpp.o
[ 41%] Building CXX object CMakeFiles/nx.dir/src/ai/hell/ballos_priest.cpp.o
[ 41%] Building CXX object CMakeFiles/nx.dir/src/ai/hell/hell.cpp.o
[ 42%] Building CXX object CMakeFiles/nx.dir/src/ai/last_cave/last_cave.cpp.o
[ 43%] Building CXX object CMakeFiles/nx.dir/src/ai/maze/balrog_boss_missiles.cpp.o
[ 44%] Building CXX object CMakeFiles/nx.dir/src/ai/maze/critter_purple.cpp.o
[ 44%] Building CXX object CMakeFiles/nx.dir/src/ai/maze/gaudi.cpp.o
[ 45%] Building CXX object CMakeFiles/nx.dir/src/ai/maze/labyrinth_m.cpp.o
[ 46%] Building CXX object CMakeFiles/nx.dir/src/ai/maze/maze.cpp.o
[ 46%] Building CXX object CMakeFiles/nx.dir/src/ai/maze/pooh_black.cpp.o
[ 47%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/balrog.cpp.o
[ 48%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/curly.cpp.o
[ 48%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/curly_ai.cpp.o
[ 49%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/misery.cpp.o
[ 50%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/npcguest.cpp.o
[ 51%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/npcplayer.cpp.o
[ 51%] Building CXX object CMakeFiles/nx.dir/src/ai/npc/npcregu.cpp.o
[ 52%] Building CXX object CMakeFiles/nx.dir/src/ai/oside/oside.cpp.o
[ 53%] Building CXX object CMakeFiles/nx.dir/src/ai/plantation/plantation.cpp.o
[ 53%] Building CXX object CMakeFiles/nx.dir/src/ai/sand/curly_boss.cpp.o
[ 54%] Building CXX object CMakeFiles/nx.dir/src/ai/sand/puppy.cpp.o
[ 55%] Building CXX object CMakeFiles/nx.dir/src/ai/sand/sand.cpp.o
[ 55%] Building CXX object CMakeFiles/nx.dir/src/ai/sand/toroko_frenzied.cpp.o
[ 56%] Building CXX object CMakeFiles/nx.dir/src/ai/sym/smoke.cpp.o
[ 57%] Building CXX object CMakeFiles/nx.dir/src/ai/sym/sym.cpp.o
[ 58%] Building CXX object CMakeFiles/nx.dir/src/ai/village/balrog_boss_running.cpp.o
[ 58%] Building CXX object CMakeFiles/nx.dir/src/ai/village/ma_pignon.cpp.o
[ 59%] Building CXX object CMakeFiles/nx.dir/src/ai/village/village.cpp.o
[ 60%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/blade.cpp.o
[ 60%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/bubbler.cpp.o
[ 61%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/fireball.cpp.o
[ 62%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/missile.cpp.o
[ 63%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/nemesis.cpp.o
[ 63%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/polar_mgun.cpp.o
[ 64%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/snake.cpp.o
[ 65%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/spur.cpp.o
[ 65%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/weapons.cpp.o
[ 66%] Building CXX object CMakeFiles/nx.dir/src/ai/weapons/whimstar.cpp.o
[ 67%] Building CXX object CMakeFiles/nx.dir/src/ai/weed/balrog_boss_flying.cpp.o
[ 67%] Building CXX object CMakeFiles/nx.dir/src/ai/weed/frenzied_mimiga.cpp.o
[ 68%] Building CXX object CMakeFiles/nx.dir/src/ai/weed/weed.cpp.o
[ 69%] Building CXX object CMakeFiles/nx.dir/src/autogen/AssignSprites.cpp.o
[ 70%] Building CXX object CMakeFiles/nx.dir/src/common/InitList.cpp.o
[ 70%] Building CXX object CMakeFiles/nx.dir/src/common/glob.cpp.o
[ 71%] Building CXX object CMakeFiles/nx.dir/src/common/misc.cpp.o
[ 72%] Building CXX object CMakeFiles/nx.dir/src/common/myfnmatch.cpp.o
[ 72%] Building CXX object CMakeFiles/nx.dir/src/common/stat.cpp.o
[ 73%] Building CXX object CMakeFiles/nx.dir/src/endgame/CredReader.cpp.o
[ 74%] Building CXX object CMakeFiles/nx.dir/src/endgame/credits.cpp.o
[ 74%] Building CXX object CMakeFiles/nx.dir/src/endgame/island.cpp.o
[ 75%] Building CXX object CMakeFiles/nx.dir/src/endgame/misc.cpp.o
[ 76%] Building CXX object CMakeFiles/nx.dir/src/graphics/bmfont.cpp.o
[ 77%] Building CXX object CMakeFiles/nx.dir/src/graphics/font.cpp.o
[ 77%] Building CXX object CMakeFiles/nx.dir/src/graphics/graphics.cpp.o
[ 78%] Building CXX object CMakeFiles/nx.dir/src/graphics/nxsurface.cpp.o
[ 79%] Building CXX object CMakeFiles/nx.dir/src/graphics/pngfuncs.cpp.o
[ 79%] Building CXX object CMakeFiles/nx.dir/src/graphics/screenshot.cpp.o
[ 80%] Building CXX object CMakeFiles/nx.dir/src/graphics/sprites.cpp.o
[ 81%] Building CXX object CMakeFiles/nx.dir/src/graphics/tileset.cpp.o
[ 82%] Building CXX object CMakeFiles/nx.dir/src/graphics/zoom.cpp.o
[ 82%] Building CXX object CMakeFiles/nx.dir/src/intro/intro.cpp.o
[ 83%] Building CXX object CMakeFiles/nx.dir/src/intro/title.cpp.o
[ 84%] Building CXX object CMakeFiles/nx.dir/src/pause/dialog.cpp.o
[ 84%] Building CXX object CMakeFiles/nx.dir/src/pause/message.cpp.o
[ 85%] Building CXX object CMakeFiles/nx.dir/src/pause/objects.cpp.o
[ 86%] Building CXX object CMakeFiles/nx.dir/src/pause/options.cpp.o
/home/mint/Desktop/nxengine-evo/src/pause/options.cpp: In function ‘void _tracks_change(Options::ODItem*, int)’:
/home/mint/Desktop/nxengine-evo/src/pause/options.cpp:413:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (result >= names.size())
       ~~~~~~~^~~~~~~~~~~~~~~
[ 86%] Building CXX object CMakeFiles/nx.dir/src/pause/pause.cpp.o
[ 87%] Building CXX object CMakeFiles/nx.dir/src/siflib/sectSprites.cpp.o
[ 88%] Building CXX object CMakeFiles/nx.dir/src/siflib/sectStringArray.cpp.o
[ 89%] Building CXX object CMakeFiles/nx.dir/src/siflib/sif.cpp.o
[ 89%] Building CXX object CMakeFiles/nx.dir/src/siflib/sifloader.cpp.o
[ 90%] Building CXX object CMakeFiles/nx.dir/src/sound/Ogg.cpp.o
[ 91%] Building CXX object CMakeFiles/nx.dir/src/sound/Organya.cpp.o
[ 91%] Building CXX object CMakeFiles/nx.dir/src/sound/Pixtone.cpp.o
[ 92%] Building CXX object CMakeFiles/nx.dir/src/sound/SoundManager.cpp.o
[ 93%] Building CXX object CMakeFiles/nx.dir/src/i18n/translate.cpp.o
[ 94%] Linking CXX executable ../bin/nx
[ 94%] Built target nx
Scanning dependencies of target extract
[ 94%] Building CXX object CMakeFiles/extract.dir/src/extract/crc.cpp.o
[ 95%] Building CXX object CMakeFiles/extract.dir/src/extract/extractfiles.cpp.o
[ 96%] Building CXX object CMakeFiles/extract.dir/src/extract/extractpxt.cpp.o
[ 96%] Building CXX object CMakeFiles/extract.dir/src/extract/extractstages.cpp.o
[ 97%] Building CXX object CMakeFiles/extract.dir/src/extract/main.cpp.o
[ 98%] Building CXX object CMakeFiles/extract.dir/src/common/misc.cpp.o
[ 98%] Building CXX object CMakeFiles/extract.dir/src/common/stat.cpp.o
[ 99%] Building CXX object CMakeFiles/extract.dir/src/stagedata.cpp.o
[100%] Linking CXX executable ../bin/extract
[100%] Built target extract

Done!
Press [Enter] to finish...
```

Runtime and Backtrace Log:
```
(gdb) run exec-file nx
Starting program: /home/mint/Desktop/nxengine-evo/bin/nx exec-file nx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe755f700 (LWP 5640)]
[New Thread 0x7fffe6d5e700 (LWP 5641)]
[New Thread 0x7ffff7fb9700 (LWP 5642)]
Loading settings...
Couldn't open file /home/mint/.local/share/nxengine/nxengine-evo/settings.dat.
No saved settings; using defaults.
Graphics::SetResolution(2)
DW: 1920, DH: 975
Disabling 1280x1024
Disabling 1600x1200
Disabling 1920x1080
Setting scaling 2
DW: 1920, DH: 975
Disabling 1280x1024
Disabling 1600x1200
Disabling 1920x1080
SDL_CreateWindow: 640x480
Graphics::InitVideo: using: opengl renderer
Graphics::FlushAll()
SIFLoader::LoadHeader: read index of 6 sections
Loading SIF section 1 from address 003b
Loading SIF section 2 from address 0437
SIFSpritesSect: loading 490 sprites
Graphics::FlushAll()
Loading font file font_2.fnt
Loading font file data/font_2.fnt
[New Thread 0x7fffe54d0700 (LWP 5643)]
 error << Failed to load tracklist >> 
Reading npc.tbl...
InitList::CallFunctions(5597b2a0): executing 61 functions...
initslopetable: generating slopetables.
initmapfirsttime: loading data/tilekey.dat.
tsc_load: loading 'data/Head.tsc' to page 0
<> tsc_compile bufsize = 1461 pageno = 0
tsc_load: loading 'data/ArmsItem.tsc' to page 2
<> tsc_compile bufsize = 9305 pageno = 2
tsc_load: loading 'data/StageSelect.tsc' to page 3
<> tsc_compile bufsize = 275 pageno = 3
Setting tick function to type 1 param 0
Setting tick function to type 6 param 0
Entering main loop...
 >> Entering stage 72: 'u'.
load_map: level size 21x16
load_map: 'data/Stage/Kings.pxm' loaded OK! - 21x16
load_pxa: reading in data/Stage/White.pxa
load_entities: reading in data/Stage/Kings.pxe
tsc_load: loading 'data/Stage/Kings.tsc' to page 1
<> tsc_compile bufsize = 359 pageno = 1
StageBossManager::SetType(0)
-- Starting on-entry script 100
Looking for script #0100 in 1 (7)
  - Started script 0100
0100:0  �����
0100:1  �����
0100:2  0056 <WAI  0050
Organya init...
load_drum: loading data/pxt/fx96.pxt into drum index 0
load_drum: loading data/pxt/fx97.pxt into drum index 2
load_drum: loading data/pxt/fx9a.pxt into drum index 4
load_drum: loading data/pxt/fx98.pxt into drum index 5
load_drum: loading data/pxt/fx99.pxt into drum index 6
load_drum: loading data/pxt/fx9b.pxt into drum index 8
Organya init done
0100:5  001a <FAI  0001
0100:8  TEXT  '\n'
0100:11  0004 <ANP  0000
ANP: Obj 56435f00 (OBJ_INTRO_DOCTOR(298)): setting state: 10 and dir: LEFT
0100:18  0056 <WAI  0097
0100:21  TEXT  '\n'
0100:24  0004 <ANP  0000
ANP: Obj 56435f00 (OBJ_INTRO_DOCTOR(298)): setting state: 1 and dir: LEFT
0100:31  0056 <WAI  0050
0100:34  TEXT  '\n'
0100:37  0004 <ANP  0000
ANP: Obj 56435f00 (OBJ_INTRO_DOCTOR(298)): setting state: 20 and dir: LEFT
0100:44  0056 <WAI  0064
0100:47  TEXT  '\n'
0100:50  0004 <ANP  0000
ANP: Obj 56435f00 (OBJ_INTRO_DOCTOR(298)): setting state: 1 and dir: LEFT
0100:57  0056 <WAI  0016
0100:60  TEXT  '\n'
0100:63  0004 <ANP  0000
ANP: Obj 56435f00 (OBJ_INTRO_DOCTOR(298)): setting state: 30 and dir: LEFT
0100:70  0056 <WAI  0050
0100:73  TEXT  '\n'
0100:76  0004 <ANP  0000
ANP: Obj 56435f00 (OBJ_INTRO_DOCTOR(298)): setting state: 40 and dir: LEFT
0100:83  0056 <WAI  0097
0100:86  TEXT  '\n'
0100:89  001b <FAO  0001
0100:92  0056 <WAI  9999
  - Stopped script 0100
Setting tick function to type 7 param 0
niku_load: couldn't open file '/home/mint/.local/share/nxengine/nxengine-evo/290.rec'
 >> music(24)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Thread 1 "nx" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6743801 in __GI_abort () at abort.c:79
#2  0x00007ffff71368b7 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff713ca06 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff713ca41 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff713cc74 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff71387b5 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00005555555dd4b0 in ?? ()
#8  0x0000000000000000 in ?? ()
```
This is my first time using gdb, so if I've provided the incorrect log please let me know and I'll correct it.

**Comment by isage** [comment]
It looks like you're missing music.json
Did you copy over data/ from the repo?
(I've fixed the relevant error, now it won't crash, but will work without music)

**Comment by 16BitWonder** [comment]
I did not copy over the most recent data/ from the repo.
Doing so resolved the crash on both platforms.
